"""empty message

Revision ID: 05eec99edab1
Revises: d7a81f170a29
Create Date: 2024-06-12 21:10:14.440402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05eec99edab1'
down_revision = 'd7a81f170a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('clickup_user_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('clickup_user_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('clickup_user_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('clickup_user_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
