"""empty message

Revision ID: 063a11abcc3f
Revises: f0d267227a25
Create Date: 2024-06-03 22:15:25.899506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063a11abcc3f'
down_revision = 'f0d267227a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
