"""empty message

Revision ID: 4f8d5aae7b3c
Revises: 34a2528bdad4
Create Date: 2024-06-16 17:39:04.189288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f8d5aae7b3c'
down_revision = '34a2528bdad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('clickup_folders')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clickup_folders', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
