"""empty message

Revision ID: 7b819482b887
Revises: e76ee3422ebc
Create Date: 2024-06-20 18:32:32.919342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b819482b887'
down_revision = 'e76ee3422ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click_team')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clickup_team_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('clickup_team_name')

    op.create_table('click_team',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('team_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('spaces', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('members', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='click_team_pkey'),
    sa.UniqueConstraint('team_id', name='click_team_team_id_key')
    )
    # ### end Alembic commands ###
