"""empty message

Revision ID: 892199f478fa
Revises: ea7718781137
Create Date: 2024-06-17 22:50:50.379510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '892199f478fa'
down_revision = 'ea7718781137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clickup_team', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('clickup_spaces', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('clickup_workspace')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clickup_workspace', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('clickup_spaces')
        batch_op.drop_column('clickup_team')

    # ### end Alembic commands ###
