"""empty message

Revision ID: c9f46a85ac0c
Revises: 05eec99edab1
Create Date: 2024-06-12 21:16:17.063193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9f46a85ac0c'
down_revision = '05eec99edab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clickup_workspaces', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('workspaces')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspaces', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('clickup_workspaces')

    # ### end Alembic commands ###
