"""empty message

Revision ID: ea7718781137
Revises: 5dc0e7fa4c22
Create Date: 2024-06-16 22:39:59.670153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea7718781137'
down_revision = '5dc0e7fa4c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clickup_workspace', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('clickup_workspaces')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clickup_workspaces', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('clickup_workspace')

    # ### end Alembic commands ###
